export const RESET_GAME_STATE = "RESET_GAME_STATE";
export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION";
export const SET_CURRENT_ROUND = "SET_CURRENT_ROUND";
export const SET_GAME_DATA = "SET_GAME_DATA";
export const SET_GAME_STATUS = "SET_GAME_STATUS";
export const SET_MARKER_LOCATION = "SET_MARKER_LOCATION";
export const SET_RETURN_BUTTON_STATUS = "SET_RETURN_BUTTON_STATUS";
export const SET_ROUND_RESULTS = "SET_ROUND_RESULTS";
