export const FETCH_MAP_FAIL = "FETCH_MAP_FAIL";
export const FETCH_MAP_REQUEST = "FETCH_MAP_REQUEST";
export const FETCH_MAP_SUCCESS = "FETCH_MAP_SUCCESS";
export const SET_SELECTED_MAP = "SET_SELECTED_MAP";
